---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

```{r}
suppressMessages(library("tidyverse"))
library(stringi)
library(plotROC)
```

```{r}
variants=read_tsv("illumina_variants.tsv")
```

```{r}
barcode1v=read_tsv("BC01.variants.freqs.txt")
barcode1v$replica = 'a'
barcode2v=read_tsv("BC02.variants.freqs.txt")
barcode2v$replica = 'b'
barcode3v=read_tsv("BC03.variants.freqs.txt")
barcode3v$replica = 'c'
minion_variants=rbind(barcode1v, barcode2v, barcode3v)

```

```{r}
minion_variants %>%
    filter(Qual == 0) %>%
    write_tsv(path="minion_variants.tsv")
```

```{r}
barcode1=read_tsv("BC01.freqs.txt")
barcode1$replica = 'a'
barcode2=read_tsv("BC02.freqs.txt")
barcode2$replica = 'b'
barcode3=read_tsv("BC03.freqs.txt")
barcode3$replica = 'c'
minion_all=rbind(barcode1, barcode2, barcode3)
```

```{r}
minion_all %>%
    filter(Qual == 0) %>%
    write_tsv(path="minion_wt_frequencies.tsv")
```


```{r}
expectedpositions=read_tsv("expectedpositions.txt")
```

```{r}
barcode1snps=read_tsv("BC01.variants.0.03.txt")
barcode1snps$replica = 'a'
barcode2snps=read_tsv("BC02.variants.0.03.txt")
barcode2snps$replica = 'b'
barcode3snps=read_tsv("BC03.variants.0.03.txt")
barcode3snps$replica = 'c'
minion_all_variants=rbind(barcode1snps, barcode2snps, barcode3snps)
minion_all_variants_positions=minion_all_variants %>%
   left_join(expectedpositions, by=c("Pos" = "Position")) %>%
   filter(State != 'Remove')
```
```{r}
minion_all_variants_positions %>%
  ggplot(aes(x=ForwardVariantCov, y=ReverseVariantCov, color=State)) + geom_point(size=0.2) + facet_wrap(~State, ncol=1)
```

```{r}
minion_all_variants_positions %>%
  mutate(StrandAF = pmin(ForwardVariantCov, ReverseVariantCov) / pmax(ForwardVariantCov, ReverseVariantCov)) 
```
```{r}
minion_all_variants_positions %>% 
       group_by(State) %>%
       summarise(n=n())
```
```{r}
minion_all_variants_positions %>%
  mutate(StrandAF = pmin(ForwardVariantCov, ReverseVariantCov) / pmax(ForwardVariantCov, ReverseVariantCov)) %>%
  filter(ForwardVariantCov > 10) %>%
  filter(ReverseVariantCov > 10) %>%
  write_tsv("minion_variants_3pc_all.tsv")
```

```{r}
forroc = minion_all_variants_positions %>%
  mutate(StrandAF = pmin(ForwardVariantCov, ReverseVariantCov) / pmax(ForwardVariantCov, ReverseVariantCov)) %>%
  filter(ForwardVariantCov > 10) %>%
  filter(ReverseVariantCov > 10) %>%
  mutate(D = ifelse(grepl("TRUE", State), 1, 0))
```

```{r}
ggplot(forroc, aes(d = D, m = Freq)) + geom_roc(labelsize=3, labelround=2) + theme_bw()
```

```{r}
nrow(forroc %>% filter(Freq > 0.06))
```

```{r}
ggplot(forroc %>% filter(Freq > 0.06), aes(d = D, m = StrandAF)) + geom_roc(labelsize=3, labelround=2) + theme_bw()
```

```{r}
mod1<-glm(D ~ Freq + StrandAF, data=forroc, family="gaussian")
prob=predict(mod1,type=c("response"))
forroc$prob = prob
melted=gather(forroc, variable, value, Freq, StrandAF, prob)
ggplot(melted, aes(d = D, color = variable, m = value)) + geom_roc(labelsize=3, labelround=2) + theme_bw()
```

```{r}
forroc %>%
  filter(prob > 0.2) %>%
  group_by(D) %>%
  write_tsv("minion_roc_classifier_snps.tsv")
```

```{r}
forroc %>%
  filter(prob > 0.2) %>%
  group_by(D) %>%
  summarise(n=n())


```

```{r}
#sens=tp/(tp+fn)
sens=160/(160+8)
print(sens)
#spec=tn/(tn+fp)
spec=8/(8+157)
print(spec)
fdr=157/(160+157)
print(fdr)
```

```{r}
minion_all_variants_positions %>%
  mutate(StrandAF = pmin(ForwardVariantCov, ReverseVariantCov) / pmax(ForwardVariantCov, ReverseVariantCov)) %>%
  filter(ForwardVariantCov > 10) %>%
  filter(ReverseVariantCov > 10) %>%
  filter(StrandAF > 0.70) %>%
  write_tsv("minion_variants_3pc_0.7strandaf.tsv")
```

```{r}
minion_all_variants_positions %>%
  ggplot(aes(x=ForwardVariantCov, y=ReverseVariantCov, color=State)) + geom_density2d() + facet_wrap(~State, ncol=1)
```

    
```{r}
minion_all_variants_positions %>%
  ggplot(aes(x=ForwardVariantCov, y=ReverseVariantCov, color=State)) + geom_point(size=0.2) + facet_wrap(~replica, ncol=1)
```

```{r}
variant_positions=inner_join(minion_all, expectedpositions, by=c("Pos" = "Position"), copy=T)
wildtype_positions=anti_join(minion_all, expectedpositions %>% filter(State == "True"), by=c("Pos" = "Position"), copy=T)
```

```{r}
wildtype_positions %>%
  filter(UngappedCoverage >= 50) %>%
  ggplot(aes(x=Freq)) + geom_histogram(bins=50) + facet_wrap(~replica, ncol=1) + theme_bw() + xlim(0.75, 1.0) + labs(title = "Wildtype allele frequencies by replica")
```

```{r}
variant_positions %>%
  filter(UngappedCoverage >= 50) %>%
  ggplot(aes(x=Freq)) + geom_histogram(bins=50) + facet_wrap(~replica, ncol=1) + theme_bw() + xlim(0.75, 1.0) + labs(title = "Alternative allele frequencies by replica")
```



```{r}
joined=inner_join(minion_variants, variants, by=c("Pos" = "Minimum"), copy=T)
p = joined %>% 
  filter(Qual == 0) %>%
  filter(modality == 'amplicon') %>%
  ggplot(aes(x=Freq, y=freq)) + geom_point(size=0.2) + stat_smooth() + xlim(0, 0.5) + ylim(0, 0.5) + xlab("Nanopore allele freq") + ylab("Illumina allele freq") + facet_wrap(~replica.x) + theme_bw(base_size=14)
p
```

```{r}
a=joined %>%
  filter(modality == 'amplicon') %>%
  filter(replica.x == replica.y) %>%
  ggplot(aes(x=Freq, y=freq)) + geom_point(size=0.2) + geom_density2d() + xlim(0, 0.5) + ylim(0, 0.5) + xlab("Nanopore allele freq") + ylab("Illumina allele freq") + facet_wrap(~replica.x~modality) + theme_bw(base_size=14)
a
```

